// Original procedural synth score: no external audio or autoplay dependencies.
export class Soundtrack {
 constructor(){this.ctx=null;this.volume=.38;this.muted=false;this.enabled=false;this.next=0;this.step=0;this.alert=1;this.timer=null;}
 async start(){if(!this.ctx){this.ctx=new AudioContext();this.master=this.ctx.createGain();this.master.connect(this.ctx.destination);this.master.gain.value=this.volume;}await this.ctx.resume();this.enabled=true;if(!this.timer)this.timer=setInterval(()=>this.schedule(),80);this.next=this.ctx.currentTime+.04;}
 setVolume(v){this.volume=v;this.master?.gain.setTargetAtTime(this.muted?0:v,this.ctx.currentTime,.05);}
 toggle(){this.muted=!this.muted;if(this.ctx)this.master.gain.setTargetAtTime(this.muted?0:this.volume,this.ctx.currentTime,.05);return !this.muted;}
 note(freq,time,duration,volume,type='triangle',slide=1){const c=this.ctx;if(!c)return;const o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.setValueAtTime(freq,time);if(slide!==1)o.frequency.exponentialRampToValueAtTime(freq*slide,time+duration);g.gain.setValueAtTime(0,time);g.gain.linearRampToValueAtTime(volume,time+.012);g.gain.exponentialRampToValueAtTime(.001,time+duration);o.connect(g);g.connect(this.master);o.start(time);o.stop(time+duration+.02);}
 schedule(){if(!this.enabled||!this.ctx||this.ctx.state!=='running')return;const c=this.ctx;const beat=60/(96+this.alert*7)/4;if(this.next<c.currentTime-.3)this.next=c.currentTime+.03;while(this.next<c.currentTime+.18){const n=this.step++,t=this.next;this.next+=beat;const roots=[55,65.406,49,58.27],root=roots[Math.floor(n/32)%4];if(n%4===0)this.note(root,t,beat*3,.12,'sawtooth');if(n%8===0)this.note(105,t,.18,.25,'sine',.35);if(n%8===4){this.note(165,t,.08,.055,'square',.4);this.note(2400,t,.035,.025,'triangle');}if(n%2===0)this.note(6000,t,.026,.025,'square');const pattern=[0,7,12,15,19,12,7,10];if(n%2===0){const freq=root*4*2**(pattern[Math.floor(n/2)%8]/12);this.note(freq,t,beat*1.7,.027+this.alert*.008,'triangle');}if(n%32===0)for(const semitone of [0,3,7])this.note(root*4*2**(semitone/12),t,beat*25,.018,'sine');}}
 effect(type){if(!this.ctx)return;const t=this.ctx.currentTime;const specs={infect:[420,.18,.12,'triangle',1.8],break:[90,.3,.2,'sawtooth',.25],shoot:[180,.08,.08,'square',.25],convert:[660,.35,.09,'sine',1.5],hurt:[100,.13,.08,'square',.5],upgrade:[520,.5,.1,'triangle',2]};this.note(...(specs[type]?[specs[type][0],t,...specs[type].slice(1)]:[300,t,.1,.08]));}
 pause(){this.enabled=false;}
 resume(){this.enabled=true;if(this.ctx)this.next=this.ctx.currentTime+.03;}
}
